"""
builder_factory_v2.py — Factory + Registry Pattern for the 10 Builders.

This module implements two design patterns:
1. **Registry Pattern**: Each builder registers itself at import time.
2. **Factory Pattern**: The `BuilderFactory` creates the right builder by name.

This allows adding new builders (e.g., AI_builder.py) without touching existing code.

Usage:
    from engine.builder_factory_v2 import BuilderFactory
    
    factory = BuilderFactory()
    factory.register_all()  # Auto-registers all 10 builders
    
    # Run a specific builder
    factory.run_builder("variables", config, strings, function_dir)
    
    # Run all builders in dependency order
    results = factory.run_all(config, strings, function_dir)
"""
from __future__ import annotations

import abc
import json
from pathlib import Path
from typing import Any, Optional


# ═══════════════════════════════════════════════════════════════════════════
# ABSTRACT BASE BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class BaseBuilder(abc.ABC):
    """Abstract base class for all builders.
    
    Every builder MUST:
    1. Have a unique `name` attribute
    2. Implement `build()` method
    3. Declare its `dependencies` (other builder names that must run first)
    4. Declare which `id_types` it handles
    """
    
    name: str = "base"
    dependencies: list[str] = []  # Builder names that must run before this one
    id_types: list[str] = []     # Which ID types this builder processes (empty = all)
    
    @abc.abstractmethod
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        """Execute this builder on the given config + strings.
        
        Args:
            config: The config.json dict (The Map)
            strings: The strings.json dict (The Execution Matrix)
            function_dir: Path to the function folder
            
        Returns:
            A dict with builder-specific results (manifests, counts, etc.)
        """
        ...
    
    def can_process(self, id_info: dict) -> bool:
        """Check if this builder should process a given ID.
        
        If `id_types` is empty, the builder processes ALL IDs.
        Otherwise, it only processes IDs whose type is in `id_types`.
        """
        if not self.id_types:
            return True
        return id_info.get("type", "") in self.id_types
    
    def get_ids(self, config: dict) -> dict:
        """Get all IDs that this builder should process."""
        return {
            code: info for code, info in config.get("ids", {}).items()
            if self.can_process(info)
        }


# ═══════════════════════════════════════════════════════════════════════════
# 1. VARIABLES BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class VariablesBuilder(BaseBuilder):
    """Converts fields to programmatic variables (String, Int, Boolean) with initialization."""
    
    name = "variables"
    dependencies = []
    id_types = ["String", "Int", "Float", "Boolean", "Email", "Phone", "URL", "Date", "Enum"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        java_vars = []
        js_vars = []
        
        for code, info in ids.items():
            original = info["original"]
            id_type = info["type"]
            
            # Java variable
            java_type = {
                "String": "String", "Email": "String", "Phone": "String", "URL": "String",
                "Date": "String", "Enum": "String",
                "Int": "int", "Float": "double", "Boolean": "boolean",
            }.get(id_type, "String")
            java_name = original.lower().replace(" ", "_").replace("-", "_")
            java_vars.append(f"    // ID: {code} | Field: {original} | Type: {id_type}\n    {java_type} {java_name};")
            
            # JS variable
            js_vars.append(f"  // ID: {code} | Field: {original}\n  let {code} = {self._default_js(id_type)};")
        
        # Write generated files
        java_content = f"// Auto-generated by VariablesBuilder\n// Total variables: {len(java_vars)}\n\n" + "\n\n".join(java_vars)
        js_content = f"// Auto-generated by VariablesBuilder\n// Total variables: {len(js_vars)}\n\n" + "\n\n".join(js_vars)
        
        (function_dir / "_variables.java").write_text(java_content, encoding="utf-8")
        (function_dir / "_variables.js").write_text(js_content, encoding="utf-8")
        
        # Update strings.json with variable declarations
        for code in ids:
            if code in strings.get("by_id", {}):
                oncreate = strings["by_id"][code].get("OnCreate", {})
                if "Variables" in oncreate:
                    # Already set by data_analyzer_v2, keep it
                    pass
        
        print(f"[VariablesBuilder] {len(java_vars)} Java vars, {len(js_vars)} JS vars", flush=True)
        return {"java_vars": len(java_vars), "js_vars": len(js_vars)}
    
    def _default_js(self, id_type: str) -> str:
        return {"String": "''", "Int": "0", "Float": "0.0", "Boolean": "false"}.get(id_type, "null")


# ═══════════════════════════════════════════════════════════════════════════
# 2. LIST BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class ListBuilder(BaseBuilder):
    """Builds repeatable data structures (Arrays, RecyclerViews, DataGrids)."""
    
    name = "list"
    dependencies = ["variables"]
    id_types = ["Array", "Object"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        manifests = []
        
        for code, info in ids.items():
            manifest = {
                "id": code,
                "field": info["original"],
                "dataset": info["dataset"],
                "type": info["type"],
                "adapter": "RecyclerView.Adapter" if info["type"] == "Array" else "CardAdapter",
                "item_layout": f"item_{info['original'].lower().replace(' ', '_')}",
            }
            manifests.append(manifest)
        
        (function_dir / "_lists_manifest.json").write_text(
            json.dumps(manifests, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[ListBuilder] {len(manifests)} list manifests", flush=True)
        return {"lists": len(manifests)}


# ═══════════════════════════════════════════════════════════════════════════
# 3. CONTROL BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class ControlBuilder(BaseBuilder):
    """Generates control logic (If/Else, Switch, For/While) from field types."""
    
    name = "control"
    dependencies = ["variables"]
    id_types = []  # Processes all IDs (control logic applies to everything)
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = config.get("ids", {})
        control_blocks = []
        
        for code, info in ids.items():
            original = info["original"]
            id_type = info["type"]
            
            block = {"id": code, "field": original, "logic": []}
            
            if id_type in ("String", "Email", "Phone"):
                block["logic"].append({
                    "type": "if",
                    "condition": f"{code}.length < 3",
                    "action": f"showError('Invalid {original}')",
                })
            elif id_type == "Int":
                block["logic"].append({
                    "type": "if",
                    "condition": f"{code} < 0",
                    "action": f"showError('{original} must be positive')",
                })
            elif id_type == "Enum":
                block["logic"].append({
                    "type": "switch",
                    "variable": code,
                    "cases": [],
                })
            
            # Add loop for array datasets
            if id_type == "Array":
                block["logic"].append({
                    "type": "for",
                    "variable": "item",
                    "iterable": code,
                    "body": f"render_item(item)",
                })
            
            control_blocks.append(block)
        
        (function_dir / "_control_manifest.json").write_text(
            json.dumps(control_blocks, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[ControlBuilder] {len(control_blocks)} control blocks", flush=True)
        return {"blocks": len(control_blocks)}


# ═══════════════════════════════════════════════════════════════════════════
# 4. OPERATOR BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class OperatorBuilder(BaseBuilder):
    """Manages math and logical operations (Add, Subtract, Compare, Concat)."""
    
    name = "operator"
    dependencies = ["variables", "control"]
    id_types = ["Int", "Float", "String"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        operations = []
        
        for code, info in ids.items():
            id_type = info["type"]
            original = info["original"]
            
            if id_type in ("Int", "Float"):
                operations.append({
                    "id": code, "field": original,
                    "ops": ["add", "subtract", "multiply", "divide", "compare"],
                })
            elif id_type == "String":
                operations.append({
                    "id": code, "field": original,
                    "ops": ["concat", "compare", "contains", "startsWith"],
                })
        
        (function_dir / "_operators_manifest.json").write_text(
            json.dumps(operations, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[OperatorBuilder] {len(operations)} operator sets", flush=True)
        return {"operations": len(operations)}


# ═══════════════════════════════════════════════════════════════════════════
# 5. FILE BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class FileBuilder(BaseBuilder):
    """Links file upload interfaces to Web APIs (FileReader, IndexedDB, Capacitor)."""
    
    name = "file"
    dependencies = []
    id_types = ["URL", "Canvas"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        file_defs = []
        
        media_dir = function_dir / "media"
        if media_dir.exists():
            for f in sorted(media_dir.iterdir()):
                if f.is_file():
                    file_defs.append({
                        "name": f.name,
                        "path": f"file:///android_asset/webapp/media/{f.name}",
                        "size": f.stat().st_size,
                        "ext": f.suffix.lower(),
                    })
        
        (function_dir / "_files_manifest.json").write_text(
            json.dumps(file_defs, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[FileBuilder] {len(file_defs)} files registered", flush=True)
        return {"files": len(file_defs)}


# ═══════════════════════════════════════════════════════════════════════════
# 6. VIEW BUILDER (The Largest Builder)
# ═══════════════════════════════════════════════════════════════════════════

class ViewBuilder(BaseBuilder):
    """The largest builder. Generates layouts, widgets, and visual structure.
    
    Reads the `View` section from strings.json for each ID and produces
    layout XML + HTML + CSS.
    """
    
    name = "view"
    dependencies = ["variables"]
    id_types = []  # Processes all IDs
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = config.get("ids", {})
        by_id = strings.get("by_id", {})
        
        layouts = {}
        html_widgets = []
        css_rules = []
        
        for code, info in ids.items():
            original = info["original"]
            id_type = info["type"]
            widget = info["widget"]
            
            # Get View config from strings.json
            view_config = by_id.get(code, {}).get("View", {})
            layout_type = view_config.get("layout", "linear_vertical")
            properties = view_config.get("properties", {})
            libraries = view_config.get("libraries", ["AndroidX"])
            
            # Generate XML layout
            xml_id = original.lower().replace(" ", "_")
            xml = self._build_xml(widget, xml_id, properties, layout_type)
            layout_name = f"item_{xml_id}"
            layouts[layout_name] = xml
            
            # Generate HTML widget
            html_widgets.append(self._build_html_widget(code, original, widget, id_type, properties))
            
            # Generate CSS
            css_rules.append(self._build_css(code, widget, id_type))
        
        # Write layouts
        layout_dir = function_dir / "_generated_layouts"
        layout_dir.mkdir(exist_ok=True)
        for name, xml in layouts.items():
            (layout_dir / f"{name}.xml").write_text(xml, encoding="utf-8")
        
        # Write HTML fragments
        html_content = f"<!-- Auto-generated by ViewBuilder -->\n<!-- Total widgets: {len(html_widgets)} -->\n\n" + "\n\n".join(html_widgets)
        (function_dir / "_view_fragments.html").write_text(html_content, encoding="utf-8")
        
        # Write CSS
        css_content = f"/* Auto-generated by ViewBuilder */\n\n" + "\n".join(css_rules)
        (function_dir / "_view_styles.css").write_text(css_content, encoding="utf-8")
        
        print(f"[ViewBuilder] {len(layouts)} XML layouts, {len(html_widgets)} HTML widgets", flush=True)
        return {"layouts": len(layouts), "widgets": len(html_widgets)}
    
    def _build_xml(self, widget: str, xml_id: str, props: dict, layout: str) -> str:
        orientation = "vertical" if "vertical" in layout else "horizontal"
        hint = props.get("hint", xml_id)
        input_type = props.get("input_type", "text")
        
        if widget == "EditText":
            return f'''<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="wrap_content"
    android:orientation="{orientation}" android:padding="8dp">
    <EditText android:id="@+id/{xml_id}"
        android:layout_width="match_parent" android:layout_height="wrap_content"
        android:hint="{hint}" android:inputType="{input_type}" />
</LinearLayout>'''
        elif widget == "Spinner":
            return f'''<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="wrap_content"
    android:orientation="{orientation}" android:padding="8dp">
    <Spinner android:id="@+id/{xml_id}"
        android:layout_width="match_parent" android:layout_height="wrap_content" />
</LinearLayout>'''
        elif widget == "Switch":
            return f'''<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="wrap_content"
    android:orientation="{orientation}" android:padding="8dp">
    <Switch android:id="@+id/{xml_id}"
        android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:text="{props.get("text", xml_id)}" />
</LinearLayout>'''
        elif widget == "ImageView":
            return f'''<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="wrap_content"
    android:padding="8dp">
    <ImageView android:id="@+id/{xml_id}"
        android:layout_width="match_parent" android:layout_height="200dp"
        android:scaleType="centerCrop" />
</FrameLayout>'''
        else:
            return f'''<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/{xml_id}"
    android:layout_width="match_parent" android:layout_height="wrap_content"
    android:padding="8dp" android:text="{hint}" />'''
    
    def _build_html_widget(self, code: str, original: str, widget: str, id_type: str, props: dict) -> str:
        hint = props.get("hint", original)
        input_type = props.get("input_type", "text")
        
        if widget == "EditText":
            return f'<div class="field-group" data-id="{code}">\n  <label>{original}</label>\n  <input type="{input_type}" id="{code}" placeholder="{hint}" class="form-input">\n</div>'
        elif widget == "Spinner":
            return f'<div class="field-group" data-id="{code}">\n  <label>{original}</label>\n  <select id="{code}" class="form-select">\n    <option value="">Select {original}</option>\n  </select>\n</div>'
        elif widget == "Switch":
            return f'<div class="field-group" data-id="{code}">\n  <label>{original}</label>\n  <label class="switch">\n    <input type="checkbox" id="{code}">\n    <span class="slider"></span>\n  </label>\n</div>'
        elif widget == "ImageView":
            return f'<div class="field-group" data-id="{code}">\n  <label>{original}</label>\n  <img id="{code}" src="" alt="{original}" class="form-image">\n</div>'
        else:
            return f'<div class="field-group" data-id="{code}">\n  <label>{original}</label>\n  <span id="{code}" class="form-text">{hint}</span>\n</div>'
    
    def _build_css(self, code: str, widget: str, id_type: str) -> str:
        return f'.field-group[data-id="{code}"] {{ margin-bottom: 12px; }}\n.field-group[data-id="{code}"] label {{ display:block; font-size:11px; color:#8b949e; margin-bottom:4px; }}'


# ═══════════════════════════════════════════════════════════════════════════
# 7. MATH BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class MathBuilder(BaseBuilder):
    """Links Canvas operations (Fabric.js/Konva.js) with math equations."""
    
    name = "math"
    dependencies = ["variables"]
    id_types = ["Int", "Float", "Canvas"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        formulas = []
        
        for code, info in ids.items():
            original = info["original"].lower()
            id_type = info["type"]
            
            if id_type in ("Int", "Float"):
                if "price" in original or "cost" in original or "fee" in original:
                    formulas.append({"id": code, "field": info["original"], "formula": f"{code} * 1.15", "description": "Calculate with VAT"})
                if "weight" in original and "height" in str(ids.keys()):
                    formulas.append({"id": code, "field": info["original"], "formula": f"weight / Math.pow(height/100, 2)", "description": "BMI calculation"})
        
        (function_dir / "_math_manifest.json").write_text(
            json.dumps(formulas, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[MathBuilder] {len(formulas)} formulas", flush=True)
        return {"formulas": len(formulas)}


# ═══════════════════════════════════════════════════════════════════════════
# 8. COMPONENT BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class ComponentBuilder(BaseBuilder):
    """Builds complex reusable components and manages their lifecycle."""
    
    name = "component"
    dependencies = ["view", "variables"]
    id_types = ["Object", "Array", "Canvas"]
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = self.get_ids(config)
        components = []
        
        icons = {"patients": "\U0001f465", "doctors": "\U0001fa7a", "nurses": "\U0001f489",
                 "medicines": "\U0001f48a", "invoices": "\U0001f4b0", "rooms": "\U0001f6cf\ufe0f",
                 "products": "\U0001f4e6", "staff": "\U0001f468\u200d\u2695\ufe0f"}
        
        for code, info in ids.items():
            ds = info.get("dataset", "")
            icon = icons.get(ds.lower(), "\U0001f4cb")
            components.append({
                "id": code, "name": f"{ds.lower()}_card",
                "dataset": ds, "icon": icon,
                "lifecycle": ["onCreate", "onBind", "onUpdate", "onDestroy"],
            })
        
        (function_dir / "_components_manifest.json").write_text(
            json.dumps(components, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[ComponentBuilder] {len(components)} components", flush=True)
        return {"components": len(components)}


# ═══════════════════════════════════════════════════════════════════════════
# 9. XML STRINGS BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class XmlStringsBuilder(BaseBuilder):
    """Generates native config files (strings.xml, AndroidManifest.xml)."""
    
    name = "xml_strings"
    dependencies = ["variables"]
    id_types = []  # Processes all IDs
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = config.get("ids", {})
        by_id = strings.get("by_id", {})
        xml_entries = []
        
        for code, info in ids.items():
            original = info["original"]
            android_name = original.lower().replace(" ", "_").replace("-", "_")
            
            # Add label string
            xml_entries.append(f'    <string name="{android_name}_label">{original}</string>')
            
            # Add values from strings.json
            values = by_id.get(code, {}).get("values", [])
            for v in values[:10]:  # Limit to 10 per field
                val = str(v.get("text", "")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                xml_entries.append(f'    <string name="{android_name}_{v.get("item_index", 0)}">{val}</string>')
        
        xml_content = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by XmlStringsBuilder -->
<!-- {len(xml_entries)} strings from {len(ids)} IDs -->
<resources>
{chr(10).join(xml_entries)}
</resources>'''
        
        (function_dir / "_final_strings.xml").write_text(xml_content, encoding="utf-8")
        
        print(f"[XmlStringsBuilder] {len(xml_entries)} XML strings", flush=True)
        return {"xml_strings": len(xml_entries)}


# ═══════════════════════════════════════════════════════════════════════════
# 10. MOREBLOCK BUILDER
# ═══════════════════════════════════════════════════════════════════════════

class MoreBlockBuilder(BaseBuilder):
    """Allows creating custom blocks (Blockly-style) and converting them to JS/Python."""
    
    name = "moreblock"
    dependencies = ["control", "operator"]
    id_types = []
    
    def build(self, config: dict, strings: dict, function_dir: Path) -> dict:
        ids = config.get("ids", {})
        blocks = []
        
        for code, info in ids.items():
            original = info["original"]
            ds = info.get("dataset", "")
            blocks.append({
                "name": f"load_{ds}_{code}",
                "type": "data_load",
                "id": code, "field": original, "dataset": ds,
            })
        
        # Add utility blocks
        blocks.extend([
            {"name": "search_all", "type": "search", "description": "Search across all datasets"},
            {"name": "show_detail", "type": "detail_view", "description": "Show item details"},
            {"name": "share_whatsapp", "type": "action", "description": "Share via WhatsApp"},
            {"name": "rate_app", "type": "action", "description": "Rate the app"},
        ])
        
        (function_dir / "_moreblocks_manifest.json").write_text(
            json.dumps(blocks, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[MoreBlockBuilder] {len(blocks)} code blocks", flush=True)
        return {"blocks": len(blocks)}


# ═══════════════════════════════════════════════════════════════════════════
# BUILDER FACTORY + REGISTRY
# ═══════════════════════════════════════════════════════════════════════════

class BuilderFactory:
    """Factory + Registry for all builders.
    
    Implements the Factory Pattern (creates builders by name) and
    Registry Pattern (builders register themselves).
    
    Adding a new builder (e.g., AI_builder) requires ZERO changes to existing code:
    1. Create a new class extending BaseBuilder
    2. Set its `name`, `dependencies`, `id_types`
    3. Register it: factory.register(MyBuilder())
    """
    
    def __init__(self):
        self._registry: dict[str, BaseBuilder] = {}
    
    def register(self, builder: BaseBuilder) -> None:
        """Register a builder instance."""
        self._registry[builder.name] = builder
        print(f"[BuilderFactory] Registered: {builder.name}", flush=True)
    
    def register_all(self) -> None:
        """Register all 10 built-in builders."""
        self.register(VariablesBuilder())
        self.register(ListBuilder())
        self.register(ControlBuilder())
        self.register(OperatorBuilder())
        self.register(FileBuilder())
        self.register(ViewBuilder())
        self.register(MathBuilder())
        self.register(ComponentBuilder())
        self.register(XmlStringsBuilder())
        self.register(MoreBlockBuilder())
    
    def get_builder(self, name: str) -> Optional[BaseBuilder]:
        """Get a builder by name."""
        return self._registry.get(name)
    
    def run_builder(self, name: str, config: dict, strings: dict, function_dir: Path) -> Optional[dict]:
        """Run a single builder by name."""
        builder = self._registry.get(name)
        if not builder:
            print(f"[BuilderFactory] Builder '{name}' not found!", flush=True)
            return None
        return builder.build(config, strings, function_dir)
    
    def _resolve_order(self) -> list[str]:
        """Resolve builder execution order based on dependencies (topological sort)."""
        # Simple dependency resolution
        order = []
        added = set()
        
        for _ in range(10):  # Max 10 iterations
            for name, builder in self._registry.items():
                if name in added:
                    continue
                # Check if all dependencies are already added
                deps_met = all(d in added for d in builder.dependencies)
                if deps_met:
                    order.append(name)
                    added.add(name)
        
        # Add any remaining (circular deps or unresolvable)
        for name in self._registry:
            if name not in added:
                order.append(name)
                added.add(name)
        
        return order
    
    def run_all(self, config: dict, strings: dict, function_dir: Path) -> dict:
        """Run all builders in dependency order.
        
        Returns a dict mapping builder name -> result.
        """
        order = self._resolve_order()
        print(f"[BuilderFactory] Execution order: {', '.join(order)}", flush=True)
        
        results = {}
        for name in order:
            try:
                result = self.run_builder(name, config, strings, function_dir)
                results[name] = result
            except Exception as e:
                print(f"[BuilderFactory] Builder '{name}' FAILED: {e}", flush=True)
                results[name] = {"error": str(e)}
        
        # Generate unified manifest
        manifest = {
            "builders_run": list(results.keys()),
            "total_builders": len(order),
            "results": results,
            "config_ids": config.get("total_ids", 0),
            "config_datasets": config.get("total_datasets", 0),
            "config_items": config.get("total_items", 0),
        }
        (function_dir / "_build_manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
        
        print(f"[BuilderFactory] Pipeline complete: {len(order)} builders, {sum(1 for r in results.values() if r and 'error' not in r)} succeeded", flush=True)
        return results


# ═══════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════

def run_pipeline(function_dir: Path, project_name: str = "UniversalApp") -> dict:
    """Run the full v2 pipeline: data_analyzer_v2 + BuilderFactory.
    
    Args:
        function_dir: Path to the function folder
        project_name: Optional project name
        
    Returns:
        Dict with all builder results
    """
    # Phase 1: Analyze data
    from engine.data_analyzer_v2 import analyze_data_files
    config, strings = analyze_data_files(function_dir, project_name)
    
    # Phase 2: Run all builders
    factory = BuilderFactory()
    factory.register_all()
    results = factory.run_all(config, strings, function_dir)
    
    return {"config": config, "strings": strings, "builders": results}


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        if path.exists():
            results = run_pipeline(path)
            print(f"\n=== Pipeline Results ===")
            for name, result in results["builders"].items():
                status = "OK" if result and "error" not in result else "FAIL"
                print(f"  {name:20s} {status}")
