"""
native_bridge.py — Generates native_bridge.js + rbac_engine.js for the v2 engine.

Phase 6: Native Bridge (Capacitor integration)
Phase 7: RBAC Engine (Role-Based Access Control)

These JS files are injected into template.html and Admin.html by the renderers.

Author: Principal Software Architect
Version: 2.1.0
"""
from __future__ import annotations

import json
from pathlib import Path


# ═══════════════════════════════════════════════════════════════════════════
# PHASE 6: NATIVE BRIDGE
# ═══════════════════════════════════════════════════════════════════════════

NATIVE_BRIDGE_JS = '''// ═══════════════════════════════════════════════════════════════════════════
// NativeBridge v2.1 — Unified API for Web + Native (Capacitor)
// Auto-generated by native_bridge.py
// ═══════════════════════════════════════════════════════════════════════════
const NativeBridge = {
    isNative: () => typeof window.Capacitor !== 'undefined' && window.Capacitor.isNativePlatform(),
    platform: () => typeof window.Capacitor !== 'undefined' ? window.Capacitor.getPlatform() : 'web',
    
    // ═══════════════════════════════════════════════════════════════════════
    // CAMERA — Capture photos (patient IDs, medical records)
    // ═══════════════════════════════════════════════════════════════════════
    async captureImage(targetId, quality = 90) {
        if (this.isNative()) {
            try {
                const { Camera } = window.Capacitor.Plugins;
                const image = await Camera.getPhoto({
                    quality: quality,
                    allowEditing: false,
                    resultType: 'Base64',
                    source: 'PROMPT'  // Camera or Gallery
                });
                const el = document.getElementById(targetId);
                if (el) {
                    el.src = 'data:image/jpeg;base64,' + image.base64String;
                    el.dataset.base64 = image.base64String;
                }
                return { success: true, base64: image.base64String };
            } catch (e) {
                console.error('[NativeBridge] Camera error:', e);
                return { success: false, error: e.message };
            }
        } else {
            // Web fallback: trigger hidden file input
            return new Promise((resolve) => {
                const input = document.createElement('input');
                input.type = 'file'; input.accept = 'image/*'; input.capture = 'environment';
                input.onchange = async (e) => {
                    const file = e.target.files[0];
                    if (!file) { resolve({ success: false, error: 'No file' }); return; }
                    const reader = new FileReader();
                    reader.onload = () => {
                        const el = document.getElementById(targetId);
                        if (el) { el.src = reader.result; el.dataset.base64 = reader.result.split(',')[1]; }
                        resolve({ success: true, base64: reader.result.split(',')[1] });
                    };
                    reader.readAsDataURL(file);
                };
                input.click();
            });
        }
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // FILE SYSTEM — Save files locally (medical reports, exports)
    // ═══════════════════════════════════════════════════════════════════════
    async saveFile(filename, base64Data, mimeType = 'application/octet-stream') {
        if (this.isNative()) {
            try {
                const { Filesystem, Directory, Encoding } = window.Capacitor.Plugins;
                await Filesystem.writeFile({
                    path: filename,
                    data: base64Data,
                    directory: Directory.Documents,
                    encoding: Encoding.Base64,
                });
                return { success: true, path: filename };
            } catch (e) {
                console.error('[NativeBridge] Filesystem error:', e);
                return { success: false, error: e.message };
            }
        } else {
            // Web fallback: download via Blob
            const blob = new Blob([atob(base64Data)], { type: mimeType });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url; a.download = filename; a.click();
            URL.revokeObjectURL(url);
            return { success: true, path: 'download' };
        }
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // BIOMETRICS — Secure admin authentication
    // ═══════════════════════════════════════════════════════════════════════
    async authenticateAdmin() {
        if (this.isNative()) {
            try {
                // Try Capacitor BiometricAuth plugin
                const { BiometricAuth } = window.Capacitor.Plugins || {};
                if (BiometricAuth) {
                    const result = await BiometricAuth.check();
                    if (result.available) {
                        const auth = await BiometricAuth.authenticate({
                            reason: 'Admin authentication required',
                            title: 'Hospital Admin',
                            subtitle: 'Please verify your identity',
                        });
                        return { success: true, verified: true };
                    }
                }
                // Fallback: PIN-based auth
                return this._pinAuth();
            } catch (e) {
                return this._pinAuth();
            }
        } else {
            return this._pinAuth();
        }
    },
    
    _pinAuth() {
        return new Promise((resolve) => {
            const pin = prompt('Enter Admin PIN:');
            resolve({ success: !!pin, verified: !!pin, method: 'pin' });
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // DEVICE INFO — Get device metadata
    // ═══════════════════════════════════════════════════════════════════════
    async getDeviceInfo() {
        if (this.isNative()) {
            try {
                const { Device } = window.Capacitor.Plugins;
                const info = await Device.getInfo();
                return {
                    platform: info.platform,
                    model: info.model,
                    osVersion: info.osVersion,
                    manufacturer: info.manufacturer,
                };
            } catch (e) {
                return { platform: 'unknown', error: e.message };
            }
        } else {
            return {
                platform: 'web',
                model: navigator.userAgent,
                osVersion: 'n/a',
                manufacturer: 'n/a',
            };
        }
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // HAPTICS — Vibration feedback
    // ═══════════════════════════════════════════════════════════════════════
    async haptic(style = 'light') {
        if (this.isNative()) {
            try {
                const { Haptics, ImpactStyle } = window.Capacitor.Plugins;
                const impactMap = { light: ImpactStyle.Light, medium: ImpactStyle.Medium, heavy: ImpactStyle.Heavy };
                await Haptics.impact({ style: impactMap[style] || ImpactStyle.Light });
            } catch (e) { /* silent fail */ }
        } else if (navigator.vibrate) {
            navigator.vibrate(style === 'heavy' ? 50 : 20);
        }
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // SHARE — Native share sheet
    // ═══════════════════════════════════════════════════════════════════════
    async share(title, text, url) {
        if (this.isNative()) {
            try {
                const { Share } = window.Capacitor.Plugins;
                await Share.share({ title, text, url, dialogTitle: title });
                return { success: true };
            } catch (e) {
                return { success: false, error: e.message };
            }
        } else if (navigator.share) {
            try {
                await navigator.share({ title, text, url });
                return { success: true };
            } catch (e) {
                return { success: false, error: e.message };
            }
        } else {
            // Fallback: copy to clipboard
            const fullText = title + ': ' + text + (url ? ' ' + url : '');
            try {
                await navigator.clipboard.writeText(fullText);
                return { success: true, method: 'clipboard' };
            } catch (e) {
                return { success: false, error: 'Share not available' };
            }
        }
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // LOCAL NOTIFICATIONS
    // ═══════════════════════════════════════════════════════════════════════
    async notify(title, body, scheduleAt = null) {
        if (this.isNative() && scheduleAt) {
            try {
                const { LocalNotifications } = window.Capacitor.Plugins;
                await LocalNotifications.schedule({
                    notifications: [{
                        title: title, body: body,
                        id: Date.now(),
                        schedule: { at: new Date(scheduleAt) },
                    }]
                });
                return { success: true };
            } catch (e) { return { success: false, error: e.message }; }
        } else if ('Notification' in window) {
            try {
                if (Notification.permission === 'granted') {
                    new Notification(title, { body });
                } else if (Notification.permission !== 'denied') {
                    const perm = await Notification.requestPermission();
                    if (perm === 'granted') new Notification(title, { body });
                }
                return { success: true };
            } catch (e) { return { success: false, error: e.message }; }
        }
        return { success: false, error: 'Notifications not available' };
    },
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) module.exports = NativeBridge;
'''


# ═══════════════════════════════════════════════════════════════════════════
# PHASE 7: RBAC ENGINE
# ═══════════════════════════════════════════════════════════════════════════

def generate_rbac_matrix(config: dict, strings: dict) -> dict:
    """Generate RBAC permission matrix for all IDs.
    
    Returns:
    {
        "5t07c": { "view": ["admin","doctor","nurse"], "edit": ["admin","doctor"], "export": ["admin"] },
        ...
    }
    """
    ids = config.get("ids", {})
    matrix = {}
    
    # Define role access patterns by field type and name
    ADMIN_ONLY = ["admin"]
    ADMIN_ACCOUNTANT = ["admin", "accountant"]
    ADMIN_DOCTOR = ["admin", "doctor"]
    ADMIN_DOCTOR_NURSE = ["admin", "doctor", "nurse"]
    ALL_ROLES = ["admin", "doctor", "nurse", "reception", "accountant"]
    
    for code, info in ids.items():
        original = info["original"].lower()
        id_type = info["type"]
        dataset = info.get("dataset", "").lower()
        
        # Determine permissions based on field name + type + dataset
        perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR_NURSE, "export": ADMIN_ONLY}
        
        # Financial fields — admin + accountant only
        if any(k in original for k in ["price", "cost", "fee", "salary", "invoice", "revenue", "expense", "profit", "bill"]):
            perms = {"view": ADMIN_ACCOUNTANT, "edit": ADMIN_ONLY, "export": ADMIN_ACCOUNTANT}
        
        # Patient medical data — admin + doctor + nurse
        elif any(k in original for k in ["diagnosis", "blood", "weight", "height", "prescription", "treatment"]):
            perms = {"view": ADMIN_DOCTOR_NURSE, "edit": ADMIN_DOCTOR, "export": ADMIN_DOCTOR}
        
        # Patient personal info — all staff
        elif any(k in original for k in ["name", "age", "gender", "phone", "address"]):
            perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR_NURSE + ["reception"], "export": ADMIN_DOCTOR_NURSE}
        
        # Room/bed assignments — admin + nurse
        elif any(k in original for k in ["room", "bed", "floor", "capacity", "occupied"]):
            perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR_NURSE, "export": ADMIN_ONLY}
        
        # Emergency data — admin + doctor + nurse
        elif any(k in original for k in ["emergency", "severity", "triage", "critical"]):
            perms = {"view": ADMIN_DOCTOR_NURSE, "edit": ADMIN_DOCTOR_NURSE, "export": ADMIN_ONLY}
        
        # Staff info — admin only
        elif any(k in original for k in ["password", "role", "username", "shift", "rating", "hire"]):
            perms = {"view": ADMIN_ONLY, "edit": ADMIN_ONLY, "export": ADMIN_ONLY}
        
        # Medicine stock — admin + nurse
        elif any(k in original for k in ["stock", "min_stock", "expiry", "supplier"]):
            perms = {"view": ADMIN_DOCTOR_NURSE, "edit": ADMIN_DOCTOR_NURSE, "export": ADMIN_ONLY}
        
        # Doctor info — admin + doctor (self)
        elif any(k in original for k in ["specialty", "patients_count", "doctor"]):
            perms = {"view": ALL_ROLES, "edit": ADMIN_ONLY, "export": ADMIN_DOCTOR}
        
        # Meta/project fields — admin only
        elif dataset == "_meta":
            perms = {"view": ADMIN_ONLY, "edit": ADMIN_ONLY, "export": ADMIN_ONLY}
        
        # Status fields — all can view, admin/doctor can edit
        elif "status" in original:
            perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR, "export": ADMIN_DOCTOR_NURSE}
        
        # Canvas/Image fields — all can view, admin/doctor can edit
        elif id_type == "Canvas" or id_type == "URL":
            perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR, "export": ADMIN_DOCTOR}
        
        # Boolean fields — admin + doctor can toggle
        elif id_type == "Boolean":
            perms = {"view": ALL_ROLES, "edit": ADMIN_DOCTOR, "export": ADMIN_ONLY}
        
        # Array/Object — admin can export, all can view
        elif id_type in ("Array", "Object"):
            perms = {"view": ALL_ROLES, "edit": ADMIN_ONLY, "export": ADMIN_ONLY}
        
        matrix[code] = perms
    
    return matrix


def generate_rbac_engine_js(rbac_matrix: dict) -> str:
    """Generate rbac_engine.js from the RBAC matrix."""
    matrix_json = json.dumps(rbac_matrix, ensure_ascii=False)
    
    return f'''// ═══════════════════════════════════════════════════════════════════════════
// RBAC Engine v2.1 — Role-Based Access Control
// Auto-generated by native_bridge.py (Phase 7)
// ═══════════════════════════════════════════════════════════════════════════
const RBACEngine = {{
    currentUserRole: 'admin', // Default: admin (set via login)
    matrix: {matrix_json},
    
    // ═══════════════════════════════════════════════════════════════════════
    // SET ROLE — Called after login
    // ═══════════════════════════════════════════════════════════════════════
    setRole(role) {{
        this.currentUserRole = role;
        this.applyPermissions();
    }},
    
    // ═══════════════════════════════════════════════════════════════════════
    // CHECK — Can user perform action on ID?
    // ═══════════════════════════════════════════════════════════════════════
    can(action, code) {{
        const perms = this.matrix[code];
        if (!perms) return true; // No restrictions = open
        const allowed = perms[action] || perms['view'];
        return allowed.includes(this.currentUserRole);
    }},
    
    // ═══════════════════════════════════════════════════════════════════════
    // APPLY — Hide/disable DOM elements based on role
    // ═══════════════════════════════════════════════════════════════════════
    applyPermissions() {{
        const elements = document.querySelectorAll('[data-code]');
        let hidden = 0, locked = 0;
        
        elements.forEach(el => {{
            const code = el.getAttribute('data-code');
            const perms = this.matrix[code];
            if (!perms) return;
            
            // Check 'view' permission
            if (!perms.view.includes(this.currentUserRole)) {{
                el.style.display = 'none';
                el.innerHTML = ''; // Security: scrub DOM to prevent inspect bypass
                hidden++;
                return;
            }}
            
            // Check 'edit' permission
            if (!perms.edit.includes(this.currentUserRole)) {{
                el.querySelectorAll('input, select, textarea').forEach(input => {{
                    input.setAttribute('readonly', 'true');
                    input.classList.add('rbac-readonly');
                }});
                locked++;
            }}
        }});
        
        console.log('[RBAC] Applied: ' + hidden + ' hidden, ' + locked + ' locked for role: ' + this.currentUserRole);
    }},
    
    // ═══════════════════════════════════════════════════════════════════════
    // LOGIN — Authenticate user + set role
    // ═══════════════════════════════════════════════════════════════════════
    async login(username, password) {{
        // In production: call backend API for JWT token
        // For now: hardcoded demo credentials
        const users = {{
            'admin': {{ password: 'admin123', role: 'admin' }},
            'doctor': {{ password: 'doc123', role: 'doctor' }},
            'nurse': {{ password: 'nurse123', role: 'nurse' }},
            'reception': {{ password: 'rec123', role: 'reception' }},
            'accountant': {{ password: 'acc123', role: 'accountant' }},
        }};
        
        const user = users[username];
        if (user && user.password === password) {{
            this.setRole(user.role);
            return {{ success: true, role: user.role }};
        }}
        return {{ success: false, error: 'Invalid credentials' }};
    }},
    
    // ═══════════════════════════════════════════════════════════════════════
    // LOGOUT
    // ═══════════════════════════════════════════════════════════════════════
    logout() {{
        this.currentUserRole = 'guest';
        this.applyPermissions();
    }},
}};

// Apply on DOM load
document.addEventListener('DOMContentLoaded', () => RBACEngine.applyPermissions());

// Export
if (typeof module !== 'undefined' && module.exports) module.exports = RBACEngine;
'''


# ═══════════════════════════════════════════════════════════════════════════
# PHASE 8: OFFLINE SYNC
# ═══════════════════════════════════════════════════════════════════════════

OFFLINE_SYNC_JS = '''// ═══════════════════════════════════════════════════════════════════════════
// OfflineSync v2.1 — IndexedDB + SQLite Sync Engine
// Auto-generated by native_bridge.py (Phase 8)
// ═══════════════════════════════════════════════════════════════════════════
const OfflineSync = {
    DB_NAME: 'hospital_app_db',
    DB_VERSION: 1,
    db: null,
    syncQueue: [],
    isOnline: navigator.onLine,
    
    // ═══════════════════════════════════════════════════════════════════════
    // INIT — Open IndexedDB
    // ═══════════════════════════════════════════════════════════════════════
    async init() {
        return new Promise((resolve, reject) => {
            const request = indexedDB.open(this.DB_NAME, this.DB_VERSION);
            
            request.onupgradeneeded = (e) => {
                const db = e.target.result;
                // Create object stores (tables) for each dataset
                if (!db.objectStoreNames.contains('datasets')) {
                    db.createObjectStore('datasets', { keyPath: 'id' });
                }
                if (!db.objectStoreNames.contains('sync_queue')) {
                    db.createObjectStore('sync_queue', { keyPath: 'id', autoIncrement: true });
                }
                if (!db.objectStoreNames.contains('cache')) {
                    db.createObjectStore('cache', { keyPath: 'key' });
                }
            };
            
            request.onsuccess = (e) => {
                this.db = e.target.result;
                console.log('[OfflineSync] IndexedDB opened:', this.DB_NAME);
                this.setupListeners();
                resolve(this.db);
            };
            
            request.onerror = (e) => {
                console.error('[OfflineSync] IndexedDB error:', e.target.error);
                reject(e.target.error);
            };
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // STORE — Save data locally
    // ═══════════════════════════════════════════════════════════════════════
    async store(datasetName, items) {
        return new Promise((resolve, reject) => {
            const tx = this.db.transaction(['datasets'], 'readwrite');
            const store = tx.objectStore('datasets');
            store.put({ id: datasetName, items: items, timestamp: Date.now() });
            tx.oncomplete = () => {
                console.log('[OfflineSync] Stored ' + items.length + ' items in ' + datasetName);
                resolve({ success: true });
            };
            tx.onerror = () => reject(tx.error);
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // RETRIEVE — Get data from local DB
    // ═══════════════════════════════════════════════════════════════════════
    async retrieve(datasetName) {
        return new Promise((resolve, reject) => {
            const tx = this.db.transaction(['datasets'], 'readonly');
            const store = tx.objectStore('datasets');
            const request = store.get(datasetName);
            request.onsuccess = () => {
                const result = request.result;
                resolve(result ? result.items : []);
            };
            request.onerror = () => reject(request.error);
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // QUEUE — Add change to sync queue (when offline)
    // ═══════════════════════════════════════════════════════════════════════
    async queueChange(action, dataset, data) {
        return new Promise((resolve, reject) => {
            const tx = this.db.transaction(['sync_queue'], 'readwrite');
            const store = tx.objectStore('sync_queue');
            store.add({
                action: action,
                dataset: dataset,
                data: data,
                timestamp: Date.now(),
                synced: false,
            });
            tx.oncomplete = () => {
                console.log('[OfflineSync] Queued: ' + action + ' on ' + dataset);
                resolve({ success: true });
            };
            tx.onerror = () => reject(tx.error);
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // SYNC — Push pending changes when back online
    // ═══════════════════════════════════════════════════════════════════════
    async sync() {
        if (!this.isOnline) {
            console.log('[OfflineSync] Offline — sync deferred');
            return { success: false, reason: 'offline' };
        }
        
        return new Promise((resolve, reject) => {
            const tx = this.db.transaction(['sync_queue'], 'readonly');
            const store = tx.objectStore('sync_queue');
            const request = store.getAll();
            
            request.onsuccess = async () => {
                const changes = request.result.filter(c => !c.synced);
                if (changes.length === 0) {
                    console.log('[OfflineSync] No pending changes');
                    resolve({ success: true, synced: 0 });
                    return;
                }
                
                console.log('[OfflineSync] Syncing ' + changes.length + ' changes...');
                // In production: POST to backend API
                // For now: mark as synced
                const syncTx = this.db.transaction(['sync_queue'], 'readwrite');
                const syncStore = syncTx.objectStore('sync_queue');
                changes.forEach(c => {
                    c.synced = true;
                    syncStore.put(c);
                });
                syncTx.oncomplete = () => {
                    console.log('[OfflineSync] Synced ' + changes.length + ' changes');
                    resolve({ success: true, synced: changes.length });
                };
            };
            request.onerror = () => reject(request.error);
        });
    },
    
    // ═══════════════════════════════════════════════════════════════════════
    // LISTENERS — Online/offline detection
    // ═══════════════════════════════════════════════════════════════════════
    setupListeners() {
        window.addEventListener('online', () => {
            this.isOnline = true;
            console.log('[OfflineSync] Back online — syncing...');
            this.sync();
        });
        
        window.addEventListener('offline', () => {
            this.isOnline = false;
            console.log('[OfflineSync] Gone offline — changes queued');
        });
    },
};

// Initialize on load
if (typeof indexedDB !== 'undefined') {
    OfflineSync.init().catch(e => console.error('[OfflineSync] Init failed:', e));
}
'''


# ═══════════════════════════════════════════════════════════════════════════
# MAIN ENTRY
# ═══════════════════════════════════════════════════════════════════════════

def generate_native_files(config: dict, strings: dict, function_dir: Path) -> dict:
    """Generate native_bridge.js, rbac_engine.js, and offline_sync.js.
    
    Also updates strings.json with RBAC permissions.
    
    Args:
        config: The config.json dict
        strings: The strings.json dict
        function_dir: Path to write the JS files
        
    Returns:
        Dict with counts and file paths
    """
    results = {}
    
    # 1. Generate native_bridge.js
    (function_dir / "native_bridge.js").write_text(NATIVE_BRIDGE_JS, encoding="utf-8")
    results["native_bridge"] = len(NATIVE_BRIDGE_JS)
    print(f"[native_bridge] native_bridge.js ({len(NATIVE_BRIDGE_JS):,} chars)", flush=True)
    
    # 2. Generate RBAC matrix + rbac_engine.js
    rbac_matrix = generate_rbac_matrix(config, strings)
    rbac_js = generate_rbac_engine_js(rbac_matrix)
    (function_dir / "rbac_engine.js").write_text(rbac_js, encoding="utf-8")
    results["rbac_engine"] = len(rbac_js)
    results["rbac_rules"] = len(rbac_matrix)
    
    # 3. Update strings.json with RBAC permissions
    by_id = strings.get("by_id", {})
    for code, perms in rbac_matrix.items():
        if code in by_id:
            by_id[code]["permissions"] = perms
        else:
            by_id[code] = {"permissions": perms}
    strings["rbac_enabled"] = True
    strings["rbac_roles"] = ["admin", "doctor", "nurse", "reception", "accountant"]
    strings["rbac_rule_count"] = len(rbac_matrix)
    
    # Re-write strings.json with RBAC
    (function_dir / "strings.json").write_text(
        json.dumps(strings, indent=2, ensure_ascii=False), encoding="utf-8")
    results["strings_updated"] = True
    
    print(f"[rbac_engine] rbac_engine.js ({len(rbac_js):,} chars, {len(rbac_matrix)} rules)", flush=True)
    
    # 4. Generate offline_sync.js
    (function_dir / "offline_sync.js").write_text(OFFLINE_SYNC_JS, encoding="utf-8")
    results["offline_sync"] = len(OFFLINE_SYNC_JS)
    print(f"[offline_sync] offline_sync.js ({len(OFFLINE_SYNC_JS):,} chars)", flush=True)
    
    return results


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        config = json.loads((path / "config.json").read_text(encoding="utf-8"))
        strings = json.loads((path / "strings.json").read_text(encoding="utf-8"))
        results = generate_native_files(config, strings, path)
        print(f"\n=== Native Bridge + RBAC + Offline Sync ===")
        for k, v in results.items():
            print(f"  {k}: {v}")
