"""
variables_builder.py — Generates Java variable declarations + Android strings.xml
from config.json (produced by data_analyzer.py).

For each field in config.json, generates:
- Java: "Type fieldName;" (camelCase)
- XML:  "<string name="field_name">Value</string>" (snake_case)
"""
import json, re
from pathlib import Path

def build(config: dict, strings: dict, function_dir: Path) -> dict:
    fields = config.get("fields_index", {})
    java_vars = []
    xml_strings = []
    
    for field_name, info in fields.items():
        code = info.get("code", "?????")
        ftype = info.get("type", "str")
        java_type = {"int": "int", "float": "double", "bool": "boolean", "str": "String"}.get(ftype, "String")
        java_name = re.sub(r'[^a-zA-Z0-9]', '_', field_name).lower()
        java_vars.append(f"    // Field: {field_name} (code={code})\n    {java_type} {java_name};")
        
        # Generate string entries from strings.json
        entries = strings.get("by_id", {}).get(code, [])
        for entry in entries[:20]:  # limit per field
            val = entry.get("text", "").replace('"', '\\"').replace("<", "&lt;").replace(">", "&gt;").replace("&", "&amp;")
            xml_strings.append(f'    <string name="{java_name}_{entry.get("item_index", 0)}">{val}</string>')
    
    # Write variables.java (reference file, not compiled)
    java_content = f"""// Auto-generated by variables_builder.py
// Total fields: {len(fields)}
// DO NOT EDIT — regenerate from config.json

"""
    java_content += "\n".join(java_vars)
    (function_dir / "_generated_variables.java").write_text(java_content, encoding="utf-8")
    
    # Write strings.xml
    xml_content = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by variables_builder.py -->
<!-- Total strings: {len(xml_strings)} -->
<resources>
{chr(10).join(xml_strings)}
</resources>"""
    (function_dir / "_generated_strings.xml").write_text(xml_content, encoding="utf-8")
    
    print(f"[variables_builder] {len(java_vars)} Java vars, {len(xml_strings)} XML strings", flush=True)
    return {"java_vars": len(java_vars), "xml_strings": len(xml_strings)}
