"""
view_builder.py — Generates Android layout XML files from config.json.
Each dataset gets a card-based layout with fields displayed.
"""
import json, re
from pathlib import Path

def build(config: dict, function_dir: Path) -> dict:
    datasets = config.get("datasets", [])
    layouts = {}
    
    for ds in datasets:
        ds_name = ds.get("name", "data")
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', ds_name).lower()
        fields = ds.get("fields", [])
        
        # Build a CardView layout for each item in this dataset
        field_views = []
        for f in fields[:8]:  # max 8 fields per card
            fname = re.sub(r'[^a-zA-Z0-9_]', '_', f["field"]).lower()
            ftype = f.get("type", "str")
            if ftype in ("int", "float"):
                field_views.append(f'        <TextView android:id="@+id/{fname}" android:layout_width="wrap_content" android:layout_height="wrap_content" android:textSize="12sp" android:textColor="#a3a3c2" android:layout_marginTop="4dp" tools:text="{f["field"]}: 123" />')
            else:
                field_views.append(f'        <TextView android:id="@+id/{fname}" android:layout_width="wrap_content" android:layout_height="wrap_content" android:textSize="13sp" android:textColor="#f5f5f5" android:layout_marginTop="2dp" tools:text="{f["field"]}: value" />')
        
        layout_xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by view_builder.py for dataset: {ds_name} -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:padding="12dp"
    android:background="#1a1a2e"
    android:layout_marginBottom="6dp">
{chr(10).join(field_views)}
</LinearLayout>"""
        
        layout_name = f"item_{safe_name}"
        layouts[layout_name] = layout_xml
    
    # Write all layouts
    layout_dir = function_dir / "_generated_layouts"
    layout_dir.mkdir(exist_ok=True)
    for name, xml in layouts.items():
        (layout_dir / f"{name}.xml").write_text(xml, encoding="utf-8")
    
    print(f"[view_builder] {len(layouts)} layouts generated", flush=True)
    return {"layouts": len(layouts), "names": list(layouts.keys())}
