"""
xml_strings_builder.py — Generates final Android strings.xml from strings.json.
Maps 5-char codes to Android string resource names.
"""
import json, re
from pathlib import Path

def build(config: dict, strings: dict, function_dir: Path) -> dict:
    codes_index = config.get("codes_index", {})
    by_id = strings.get("by_id", {})
    
    xml_entries = []
    
    for code, entries in by_id.items():
        field_name = codes_index.get(code, code)
        android_name = re.sub(r'[^a-zA-Z0-9_]', '_', field_name).lower()
        
        for entry in entries:
            val = str(entry.get("text", ""))
            # XML-escape
            val = val.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            val = val.replace('"', '\\"').replace("'", "\\'")
            idx = entry.get("item_index", 0)
            xml_entries.append(f'    <string name="{android_name}_{idx}">{val}</string>')
        
        # Also add a default/label string
        xml_entries.append(f'    <string name="{android_name}_label">{field_name}</string>')
    
    xml_content = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by xml_strings_builder.py -->
<!-- {len(xml_entries)} strings from {len(by_id)} fields -->
<resources>
{chr(10).join(xml_entries)}
</resources>"""
    
    (function_dir / "_final_strings.xml").write_text(xml_content, encoding="utf-8")
    
    print(f"[xml_strings_builder] {len(xml_entries)} XML string entries", flush=True)
    return {"xml_strings": len(xml_entries)}
